### ISSUE TITLE
Send recording as a stream

### ISSUE THREAD

**Issue by carpogoryanin** [blueimp/record-screen#2]
Hi! It's not an issue, just a question.

Is it possible with your library don't save screen recording as video file but provide as a stream. I don't know correct video vocabulary, so I will clarify: I want to record screen and share by some url as a streaming service, is it possible? So I need a stream (as I understand) and send this stream to some streaming library that can share stream by HTTP.

Thx!

**Comment by blueimp** [comment]
Hi @carpogoryanin,

while I don’t have plans to add streaming support to this library, I have a separate project that might be a good fit for your use case:

https://github.com/blueimp/mjpeg-server
> MJPEG Server implements MJPEG over HTTP using FFmpeg or any other input source capable of piping a multipart JPEG stream to stdout.

**Comment by blueimp** [comment]
Closing this as resolved due to no further comments.
