### ISSUE TITLE
Connection to tcp://localhost:9000 failed: Connection refused

### ISSUE THREAD

**Issue by ramazanulucay** [blueimp/record-screen#5]
Hi,

My operation system's Macos Catalina. I try this package for screen recording but, It does not working.

Error: Command failed: ffmpeg -y -r 15 -f mjpeg -i http://localhost:9000/ -pix_fmt yuv420p /tmp/test.mp4
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tcp @ 0x7f8267700140] Connection to tcp://localhost:9000 failed: Connection refused
http://localhost:9000/: Connection refused

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'ffmpeg -y -r 15 -f mjpeg -i http://localhost:9000/ -pix_fmt yuv420p /tmp/test.mp4'
}

**Comment by blueimp** [comment]
If you're using the mjpeg input, you also need an MJPEG server running that ffmpeg can connect to, e.g. https://github.com/blueimp/mjpeg-server

I should point out that this library is aimed at recording remote screens, as its original use case was for recording selenium/webdriver controlled browser sessions from a Docker container.

If you want to record a MacOS or Windows desktop directly, you might wanna construct your own ffmpeg command line or use a a more generalized Node.js ffmpeg wrapper:
https://trac.ffmpeg.org/wiki/Capture/Desktop

See also #3

**Comment by ramazanulucay** [comment]
Thank you, I want to record application window.
